// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (sql.Result, error)
	CreateQuotation(ctx context.Context, arg CreateQuotationParams) (sql.Result, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteCategory(ctx context.Context, id int64) error
	DeleteQuotation(ctx context.Context, id int64) error
	DeleteService(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetQuotation(ctx context.Context, id int64) (Quotation, error)
	GetServiceByID(ctx context.Context, id int64) (Service, error)
	GetServiceBySeller(ctx context.Context, sellerID int64) ([]Service, error)
	GetUser(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListCategory(ctx context.Context, arg ListCategoryParams) ([]Category, error)
	ListQuotations(ctx context.Context, arg ListQuotationsParams) ([]Quotation, error)
	ListService(ctx context.Context, arg ListServiceParams) ([]Service, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (sql.Result, error)
	UpdateQuotation(ctx context.Context, arg UpdateQuotationParams) (sql.Result, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (sql.Result, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
